apiVersion: v1
kind: Service
metadata:
    name: beautech-master-web-app
    labels:
        app: beautech-master-web-app
spec:
    selector:
        app: beautech-master-web-app
    ports:
        - port: 80
          targetPort: 80
    type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: beautech-master-web-app
spec:
    selector:
        matchLabels:
            app: beautech-master-web-app
    replicas: 1
    strategy:
        type: RollingUpdate
        rollingUpdate:
            maxUnavailable: 0
            maxSurge: 1
    revisionHistoryLimit: 10
    template:
        metadata:
            name: beautech-master-web-app
            labels:
                app: beautech-master-web-app
        spec:
            nodeSelector:
                pool: systempool
            containers:
                - name: beautech-master-web-app
                  image: registry.gitlab.com/accto-go-cloud/web-apps/beautech-master-web-app:prod
                  imagePullPolicy: Always
                  ports:
                      - containerPort: 80
            imagePullSecrets:
                - name: regcred

